M48
; DRILL file {KiCad 6.0.4+dfsg-1+b1} date Wed 18 May 2022 11:29:00 AM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-18T11:29:00-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.0Y-1.0
X1.0Y-5.0
X10.0Y-1.0
X10.0Y-5.0
T0
M30
